module.exports = {
	"chineseyuan" : "cny",
	"cny" : "cny",
	"usdollar" : "usd",
	"usd" : "usd",
	"euro" : "eur",
	"japaneseyen" : "jpy",
	"southkoreanwon" : "krw",
	"hongkongdollar" : "hkd",
	"indianrupee" : "inr",
	"britishpound" : "gbp",
	"australiandollar" : "aud",
	"swissfranc" : "fr",
	"turkishlira" : "try",
	"russianruble" : "rub",
	"mexicanpeso" : "mxn",
	"swedishkrona" : "sek",
	"thaibaht" : "thb"
};